[project]
name = "report-generator-template"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = ["pydoover[reports]>=1.4.2"]

[project.scripts]
export-config = "report_generator_template.app_config:export"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/report_generator_template"]

[dependency-groups]
dev = ["pytest>=8.3.5"]
