name: Lint and Test Code

on:
  pull_request:
    branches-ignore:
      - main

jobs:
  lint:
    name: Lint Code
    uses: ./.github/workflows/run-linting.yml
    secrets: inherit

  test:
    name: Test Code
    uses: ./.github/workflows/run-tests.yml
    secrets: inherit

  validate:
    name: Validate Schemas
    uses: ./.github/workflows/validate-schema.yml
    secrets: inherit
